apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: http-listener
spec:   
  port: 8080
  protocol: HTTP
  securityModel: XFP # X-Forwarded-Proto 
  hostBinding:  
    namespace:
      from: SELF