apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wbplayeconomy-tls-cert
spec:
  secretName: wbplayeconomy-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "wbplayeconomy.eastus.cloudapp.azure.com"