envVariables:
  ServiceSettings__MessageBroker: SERVICEBUS
  ServiceSettings__KeyVaultName: wbplayeconomy

resources:
  limits:
    memory: "128Mi"
    cpu: "150m"

container:
  liveness:
    path: /health/live
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
  readiness:
    path: /health/ready
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5

service:
  type: ClusterIP
  port: 80